import "NetworkActionViewModel.idl";

namespace Messenger
{
    [default_interface]
    runtimeclass ServerPage : Windows.UI.Xaml.Controls.Page
    {
        ServerPage();
        NetworkActionViewModel ClientNetworkActionViewModel { get; };
        NetworkActionViewModel ServerNetworkActionViewModel { get; };
    }
}
